### ISSUE TITLE
Using Permalink Manager to set a custom link, the page cannot be queried through nodeByUri, how can I solve this problem?

### ISSUE THREAD

**Issue by youdianfan** [wpengine/faustjs#1313]
I used the CPT plug-in to create an Event type, and then reset the fixed link through Permalink Manager. Then I used wp-graphql to query, but the page could not be queried. Return null

![image](https://user-images.githubusercontent.com/27018910/222968270-5e88919e-a314-4e9f-baa6-1c805acd1a66.png)

I can query the information through the old link, but it returns a new uri. I expect to query the content through `/events/test/`. Is there any way to solve this problem?

![image](https://user-images.githubusercontent.com/27018910/222968313-1983c1b3-a016-40d7-8740-1cc562eaab1a.png)

This is my Permalink Manager Settings

![image](https://user-images.githubusercontent.com/27018910/222968006-edbbb6fb-86b4-4e04-8bc9-2a6924d64314.png)

My CPT, Events Post Type Settings

``` php
function cptui_register_my_cpts_event() {
	$labels = [
		"name" => esc_html__( "Events", "twentytwentytwo" ),
		"singular_name" => esc_html__( "Event", "twentytwentytwo" ),
		"menu_name" => esc_html__( "Events", "twentytwentytwo" ),
		"all_items" => esc_html__( "All Events", "twentytwentytwo" ),
		"add_new_item" => esc_html__( "Add New Event", "twentytwentytwo" ),
		"edit_item" => esc_html__( "Edit Event", "twentytwentytwo" ),
		"new_item" => esc_html__( "New Event", "twentytwentytwo" ),
		"view_item" => esc_html__( "View Event", "twentytwentytwo" ),
		"view_items" => esc_html__( "View Events", "twentytwentytwo" ),
		"search_items" => esc_html__( "Search Event", "twentytwentytwo" ),
		"not_found" => esc_html__( "No Events found", "twentytwentytwo" ),
		"not_found_in_trash" => esc_html__( "No Events found in Trash", "twentytwentytwo" ),
		"parent" => esc_html__( "Parent Event:", "twentytwentytwo" ),
		"featured_image" => esc_html__( "Featured image for this event", "twentytwentytwo" ),
		"parent_item_colon" => esc_html__( "Parent Event:", "twentytwentytwo" ),
	];

	$args = [
		"label" => esc_html__( "Events", "twentytwentytwo" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => true,
		"rewrite" => [ "slug" => "event", "with_front" => true ],
		"query_var" => true,
		"menu_icon" => "dashicons-calendar-alt",
		"supports" => [ "title", "editor", "thumbnail", "excerpt", "custom-fields" ],
		"show_in_graphql" => true,
		"graphql_single_name" => "Event",
		"graphql_plural_name" => "Events",
	];

	register_post_type( "event", $args );
}

add_action( 'init', 'cptui_register_my_cpts_event' );
```

My Permalink Manager Settings
`events/%event%`
![image](https://user-images.githubusercontent.com/27018910/222968625-b4d633ca-f5d4-43a0-8bc2-bf66eb0012bc.png)

My plugin information

![image](https://user-images.githubusercontent.com/27018910/222968781-81454101-7813-405a-9edb-0cad469fcfbe.png)

**Comment by youdianfan** [comment]
Is there any way to solve this problem, or some other way?

**Comment by theodesp** [comment]
Hey @youdianfan for what I know so far, we only support a specific permalink structure as explained in the getting started guide:

https://faustjs.org/docs/getting-started#check-your-permalinks

If you have a different permalink structure you need to make sure that the relative path of the current page is can resolve the  correctly with WPGraphQL.

When accessing page for example `/events/%postname%` we try to resolve a url for the seedQuery and passed as a parameter to this request. You can see the code section here:

https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/getWordPressProps.tsx#L62-L69

Currently we just assume that the user has one `[...wordPressNode].js` file on the root `/pages` folder so if you visit that page the resolvedUrl will be:

`/events/this-is-new-post`

So if we feed that to the `seedQuery` it will resolve to `null` since your permalinks do not handle that route. 

Maybe we can add another filter for the `resolvedUrl` of the seedQuery just before the call but I'm not sure about it yet.

```js
const resolvedUrl = hooks.applyFilters('seedQueryResolvedUrl', resolvedUrl, {
    seedQuery,
  });
```

**Comment by theodesp** [comment]
Feel free to submit a PR.

**Comment by youdianfan** [comment]
@theodesp Thank you very much for your detailed reply. I have also fed back this question in WPGraphQL. Their relevant reply may be rested in the next version, but they are not sure whether the next version can fully fix this problem.

**Comment by theodesp** [comment]
@youdianfan  I'm closing this one since it is dependent of WPGraphQL.
