### ISSUE TITLE
Request: Default block improvements

### ISSUE THREAD

**Issue by justlevine** [wpengine/faustjs#1344]
The current provided default block wraps everything in an unnecessary `<div>`. While native React requires us to only `dangerouslySetInnerHTML` on a valid HTML tag, it provides an extra barrier for getting Faust set up. I recommend the following changes:

1. Provide a WP filter to let a user provide their own default block. That way a user can choose to wrap them in `span` or use an external library to ditch the wrapper.

2. Consider using `html-react-parser` (or another library) for the default block. Even though its an external dependency, I believe the benefits of both dropping the router, and using parser options to replace html tags with components (e.g. next/image) outweigh that concern. (And of course, if so, please make the parser options filterable as well.

**Comment by theodesp** [comment]
@justlevine We have a ticket in our backlog to configure this. I will prioritise for next sprint.

The API would be a bit simpler though:

* There will be a configuration to hook into the resolve block template function so that the user can supply its both their ow `DefaultBlock` or the logic to match the templates.
* Not sure about the html-react-parser since if you have the option to customize the `DefaultBlock` you can also bring your own parser like html-react-parser.

**Comment by blakewilson** [comment]
Closed via #1368
