### ISSUE TITLE
Bug: onClick not working from within wp-blocks

### ISSUE THREAD

**Issue by ivantomicic** [wpengine/faustjs#1553]
If I would have very simple function inside one of wp-blocks blocks, such as 

`<button onClick={() => alert("👻 ")}>Click This Button For Alert</button>`

It would not work after build, if I call same component even outside of WordpressBlockViewer, clicking that button would show alert, but not from within WordpressBlockViewer.

This is is just basic example, however none of interaction works from within wp-blocks after build

## Applicable Versions

- `@faustjs/core` version: 1.1.1
- `@faustjs/react` version: 17.0.2
- `@faustjs/next` version: 12.1.6
- WordPress version: 6.3

**Comment by theodesp** [comment]
Hey @ivantomicic could you provide a small reproducible example please? We will take a look. Thank you.

**Comment by ivantomicic** [comment]
Absolutely... I made something very quickly, here, you will see two buttons, both called from same component but one within blocks and one outside...

https://faustwp-blocks-possible-bug.vercel.app/possible-bug

First one (outside) works and second one does not.

Here's repo https://github.com/ivantomicic/faustwp-blocks-possible-bug

**Comment by ivantomicic** [comment]
Thank you! It does seem like this makes it work.

I'm just wondering, why do we need to define that name? Can it default to its name? It seems like this would be bit redundant as I'm only showing CoreParagraph as example here, however in real project, I would have multiple custom blocks created, and while its easy to add that config, it seems like it could default to its name?

**Comment by theodesp** [comment]
@ivantomicic This is how the `WordpressBlockViewer` needs to match the data with the React Component.

On the one hand we have block data that you get from the GraphQL API
```
"editorBlocks" = [
            {
              "name": "core/paragraph",
              "__typename": "CoreParagraph"
            },
{
              "name": "core/heading",
              "__typename": "CoreHeading"
            },
```

On the other hand we have React Components like the one that you defined for `CoreParagraph`.

However when you do export your components we really need to know how to match them:

```
export default {
	CoreParagraph,
};
```

In a production build this will transpiled as:

```js
export default {
   'a': CoreParagraph 
}
```

or `CoreParagraph.name = 'a'`

Here `a` is a random string that Webpack assignes as the exported symbol.

So out of the possible options to match either the `name` or the `__typename` properties nothing will match since:

`a !== 'CoreParagraph'` and `a !== 'core/paragraph'`

One way to ensure that the exported name is always fixed you can do is:

```
export default {
 'CoreParagraph': CoreParagraph
};
```
This will ensure that the exported `name` is always `CoreParagraph` instead of a mangled name.

`'CoreParagraph' !== 'CoreParagraph'` match!!

Another way is with either `displayName` or `config.name`. 

```
CoreParagraph.displayName = 'CoreParagraph';`
```

Here since the `CoreParagraph.name` will not match, we check the `CoreParagraph.displayName` which will match.

**Comment by ivantomicic** [comment]
I understand! Thank you so much for your help!
