### ISSUE TITLE
Bug: graphql health-check fails when using Local wordpress with https

### ISSUE THREAD

**Issue by ryan-snyder** [wpengine/faustjs#1772]
## Environment
- `@faustwp/core` version: 2.1
- `@faustwp/cli` version: 2
- WordPress version: 6.4.2

## Description

When using a local wordpress site with https, setting `NEXT_PUBLIC_WORDPRESS_URL` to `https://somesite.local` causes `npm run dev` to fail during the graphql health-check. This is because `fetch('https://somesite.local/index.php?graphql')` will throw the error `DEPTH_ZERO_SELF_SIGNED_CERT`
## Steps to Reproduce

1. Set up a local wordpress site with Local
2.  Copy the getting-started-example and follow the getting-started page
3.  set `NEXT_PUBLIC_WORDPRESS_URL` to your wordpress site url with https
## Expected vs. Actual Behavior

`npm run dev` should work with a local wordpress site using https

A potential fix would be https://stackoverflow.com/questions/52478069/node-fetch-disable-ssl-verification

**Comment by blakewilson** [comment]
Hi @ryan-snyder, thanks for creating the issue. I have seen this as well, for example: https://github.com/wpengine/faustjs/issues/1702#issuecomment-1907405920

We will look into this and response when we have a solution/fix. In the meantime, you can use the `--skip-health-checks` flag:

```bash
faust dev --skip-health-checks
```

**Comment by matthewguywright** [comment]
@ryan-snyder I had some time to look into this issue and I can see that the easiest and most efficient way forward is to add an environmental variable to just your `.env.local` or any other .env files you want to bypass https. We don't recommend doing this is production environments due to security risks. Please add this to your `.env.local` and let us know if that fixes your issue.

**Add this to `.env.local`**
`NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by matthewguywright** [comment]
@ryan-snyder Closing due to no response/activity. If you continue having this issue in the future please feel free to reach out again and create another issue. Thanks.
