### ISSUE TITLE
Preview Overhall

### ISSUE THREAD

**Issue by moonmeister** [wpengine/faustjs#370]
As discussed the other day. Preview handling needs a big overhaul to fix bugs and work better with various front-end frameworks. 

## New Features

- Don't require `/preview` prefix. Allow for doing previews based on the query params or custom prefix.
- Handle previews for published and draft content.
- Handle previews for custom post types or any other non-post/page content.
- ...

## Existing bugs
- When clicking page previews from editing the URL directs to the WP url and not localhost (aka headless url). Posts correctly directly to the headless app. THe "Preview" link available on the page list works, just not in the editing page.
- sometimes when following a preview link the `/preview` is after the page route, not before. 

## Todo
- [ ] Research needs to be done around WP previews and all the various ways it handles previews for different content types. 
- [ ] ...

## Related issues
https://github.com/WordPress/gutenberg/issues/33616#issuecomment-885056043

Let's use this topic to add any bugs, conversation, and research to work towards a new plan. Feel free to edit this original post to add things to the lists above.

**Comment by moonmeister** [comment]
@jordanmaslyn points out tat in next we no longer need the preview prefix due to https://nextjs.org/blog/next-10-2#routing-based-on-headers-and-query-string-parameters

**Comment by wjohnsto** [comment]
Yes, I have tested and verified that the preview redirects work. With the following config:

```js
module.exports = {
  async redirects() {
    return [
      {
        source: "/",
        has: [
          {
            type: "query",
            key: "preview",
            value: "true",
          },
        ],
        destination: "/foo/bar",
        permanent: false,
      },
    ];
  },
};
```

`http://localhost:3000?preview=true&p=34` redirects to `http://localhost:3000/foo/bar?preview=true&p=34`

**Comment by wjohnsto** [comment]
I wonder if we can get away with only this:

```js
module.exports = {
  async redirects() {
    return [
      {
        source: "/((?!preview).*)",
        has: [
          {
            type: "query",
            key: "preview",
            value: "true",
          },
        ],
        destination: "/preview",
        permanent: false,
      },
    ];
  },
};
```

This would match any route that isn't `/preview` with `preview=true` and redirect, but it doesn't carry the path to the destination. I am aware of a possible WordPress revision URL that might look something similar to `/post-31/?preview_id=36&preview_nonce=9ff513087e&preview=true&p=36`. In this case, do we need to capture `post-31` and pass it to the destination? I don't think it's necessary since we have all the necessary information we need to get the preview from the query params (at least I think we do).

**Comment by moonmeister** [comment]
I'd like a world where no redirect is required, it just works on the normal route.

**Comment by wjohnsto** [comment]
Yeah, I think the reason it won't work that way is it doesn't currently play well with Next SSG as you don't have access to query params inside `getStaticProps`. There is an option where instead of redirecting to `/preview` you redirect to an API route that will use [Next's preview functionality](https://nextjs.org/docs/advanced-features/preview-mode) and redirect to the proper URL with it. So with a config like this:

```js
module.exports = {
  async redirects() {
    return [
      {
        source: "/((?!preview).*)",
        has: [
          {
            type: "query",
            key: "preview",
            value: "true",
          },
        ],
        destination: "/api/preview",
        permanent: false,
      },
    ];
  },
};
```

And a `pages/api/preview.ts` something like this:

```ts
import { Page, Post } from "client";
import { NextApiRequest, NextApiResponse } from "next";

export default async (req: NextApiRequest, res: NextApiResponse) => {
  // ... do some auth stuff to get the access token
  const accessToken = '';

  // Get the preview data based on the query params.
  const previewData: Post | Page = await getPreviewData(req.query);

  // Enable Preview Mode by setting the cookies
  res.setPreviewData(previewData);

  // Redirect to the path from the fetched post
  // We don't redirect to req.query.slug as that might lead to open redirect vulnerabilities
  res.redirect(previewData.uri);
};
```

**Comment by moonmeister** [comment]
Yeah, if the only benefit is the url change then probably not worth it. If as we test there's any stability/experience/etc improvements that one method could provide it might be worth considering. If this was all SSR it wouldn't be a problem, correct?

**Comment by wjohnsto** [comment]
Yeah, if you are not using static site generation for your pages/posts then you can do everything you need. You have access to the request cookie and query string within `getServerSideProps`.

If Next.js would provide a way to get access to the cookie/query string within `getStaticProps` when using `fallback: 'blocking'` and further provide a mechanism for not caching the resulting page that would be ideal.

**Comment by moonmeister** [comment]
Is there no way to force a page to SSR even if it's normally static?

**Comment by wjohnsto** [comment]
You can use `fallback: 'blocking'` in `getStaticPaths` and it will SSR any page that isn't already cached. However, you still won't get access to the cookie/query and you also have no way to prevent Next from caching the result.

**Comment by moonmeister** [comment]
If you're suggesting we break previews if someone tries to do ISR/static pages then I don't agree. We need to allow flexibility, I'd take a I'll change any day if that was the trade off. But maybe I'm miss understanding your point @blakewilson

**Comment by wjohnsto** [comment]
I think Blake is saying if someone were to put `getStaticProps` on a page that is attempting to get previews via `usePreview` then we could throw an error. I'm not sure it's possible to know that `getStaticProps` exists on our end without requiring some configuration in the `next.config.js`.

I think `usePreview` should have some error handling to inform you if query params are missing, but I don't think we need much more than that.

I do think it would be more trouble than it's worth to craft something simply to support SSG for previews, however without going through all of that support (or some change to Next.js) we will be unable to support standard WP permalinks for previews, at least in Next.js, since you will also probably want to statically generate your posts and pages.

**Comment by moonmeister** [comment]
That makes more sense. Yeah, I think the goal of this should be flexibility. If next can't support a re-write, than fine but let's make sure sveltekit or something else that doesn't need that still works. Sounds like we're all on the same page.

**Comment by blakewilson** [comment]
Posting this here as it might be helpful for supporting the different types of preview URLs. These are the preview URLs on a vanilla WordPress installation:

Existing post preview:
/hello-world/?preview_id=1&preview_nonce=3d6fd3a374&preview=true

Existing page preview:
/sample-page/?preview_id=2&preview_nonce=6e61f798ea&preview=true

New post preview:
/?p=6&preview=true

New page preview:
/?page_id=9&preview=true

Draft page preview:
/?page_id=3&preview=true

**Comment by bebjakub** [comment]
> I feel that there is not really a need for SSG previews. I think if we stuck with just CSR/SSG for our previews implementation, and it was documented properly, it would be a better experience for the users.
> 
> To @moonmeister point, we could maybe look for an exported `getStaticProps` function and throw an error saying that previews are only supported in CSR/SSR.

@blakewilson I agree, that we don't need SSR for previews. 
There are many scenarios where public content is not updated frequently and SSG is enough, so we don't need serverless functions for SSR or ISR just a CDN and build environment. 
In this case, when nextjs is exported, we cannot use nextjs rewrites, so for the previews, we have to use CSR only. Please keep it in the mind during implementation. 
Have a good time, faustjs looks very promising!  :)
