### ISSUE TITLE
PROPOSAL: Gutenberg bridge

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#424]
Let's collect ideas on how to best support Gutenberg here

**Comment by moonmeister** [comment]
Previous work https://h7u9osp3i8a4gi05at51bk1i1.js.wpenginepowered.com/

**Comment by Jason-Murray** [comment]
After chatting with @wjohnsto I think this represents something simple now, which will become more complex later, when more details of how Gutenberg will work for full site editing have been finalised.

**Style Sharing**
As a starting point, the default Gutenberg blocks can be displayed correctly FE by including these styles from WP core in our FE project:
```
/wp-includes/css/dist/block-library/style.css
/wp-includes/css/dist/block-library/theme.css
```
Linking our FE styling back in to the editor to give a more seemless editing can be done by providing a stylesheet from the FE project to be used with `editor-styles`.

This becomes more complicated with blocks that are not provided by WP core, and even more so when blocks begin using the `enqueue_block_assets` action.

I'm not sure how we can improve this and maintain loose coupling between WP and FE.

**Static HTML to Components in FE**
In the interim while full site editing is being finalised, something similar to https://www.npmjs.com/package/@frontity/html2react could be used to switch blocks back to components in the FE project.

**Components sent from CMS rather than static HMTL**
Very far out in the timeline, we could be looking at receiving components from WP rather than static HTML.

**Comment by josephfusco** [comment]
Closing for now. Will reevaluate in the future.
