### ISSUE TITLE
System is unable to find /authors/<author-slug> page 

### ISSUE THREAD

**Issue by Pritha-Roy** [wpengine/faustjs#674]
Whenever I'm trying to create a new section which will show the authors detail page with all the posts created by the author, system is redirecting me to the 404 page. I'm following the [category] example but its not working in my case. Any idea why?

**Comment by blakewilson** [comment]
Hey @Pritha-Roy 👋  Could you please share some of the code you've tried or a reproduction.

**Comment by priard** [comment]
> Whenever I'm trying to create a new section which will show the authors detail page with all the posts created by the author, system is redirecting me to the 404 page. I'm following the [category] example but its not working in my case. Any idea why?

This is because is404 will not understand the context for [customSlug] and will return true for notFound: in getStaticProps.

If you remove the line "notFound: await is404 (context, {client})," your page will work when you refer to an existing author based on [CustomSlug], but if the author is not found, it will not return 404 for obvious reasons.

You have to write your own logic to check if the author exists and then return a boolen for notFound in getStaticProps.

**Comment by theodesp** [comment]
@priard and @Pritha-Roy We did faced the same issue when building a Blueprint site. We have a temporary solution for checking for 404 page for CPT:

https://github.com/wpengine/atlas-blueprint-portfolio/blob/4d1c1f1bf51069586255a5c5bb9f7d3eba5ab181/src/utils/is404Cpt.js#L11

**Comment by josephfusco** [comment]
Hey @Pritha-Roy we have a ticket in our backlog for this and are planning to address this in future versions of Faust.
