### ISSUE TITLE
Bug: Unable to create/edit Custom Fields (ACF) with FaustWP 7.3

### ISSUE THREAD

**Issue by aitoraznar** [wpengine/faustjs#752]
## Applicable Versions

- WordPress version: 5.8.2 or 5.9
- FaustWP version: 7.3 (Not happening in FaustWP 7.1)

## Steps To Reproduce

1. Try to create new or edit  existing "Custom Field" through the WP dashboard

## The current behavior

Throws `Undefined property: WP_Post_Type::$graphql_single_name`
![Screenshot 2022-01-28 at 09 47 29](https://user-images.githubusercontent.com/2470879/151517120-ec205db1-c2d4-4bff-b742-be4ba2f44ff5.png)

## The expected behavior
Not erroring

**Comment by theodesp** [comment]
@aitoraznar This is a really strange case because I wasn't able to reproduce this on a clean Local install WP 5.9 with Faust.js 0.7.3 and ACF 5.11.4.
<img width="1613" alt="Screenshot 2022-01-28 at 10 41 39" src="https://user-images.githubusercontent.com/328805/151533116-5c698119-6731-4538-8adb-67dcdc563ec9.png">

This piece of code was added in 0.7.2 in this [commit](https://github.com/wpengine/faustjs/commit/c74ce4f80f933ab73ffed43697d32e35d0b40311#diff-e7d71bae262ad10f2716f4f695660a50636e3ee031f1302628ea825422cad5ef) for handling CPT previews.

Is there anything else that we are missing here?

**Comment by aitoraznar** [comment]
I'll try to setup a reproducible project. Thanks
